import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { SearchIcon } from "@heroicons/react/outline";
import LoginModal from "../components/LoginModal";
import SignupModal from "../components/SignupModal";
import { useSelector } from "react-redux";
import CommentModal from "../components/CommentModal";
import {
  BadgeCheckIcon,
  CheckCircleIcon,
  CheckIcon,
  DotsHorizontalIcon,
} from "@heroicons/react/solid";

export default function Home() {
  const user = useSelector((state) => state.user);
  const tweet = useSelector((state) => state.open.tweet);

  return (
    <div className="text-white">
      <Head>
        <title>FES Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />

        <div className="hidden p-4 lg:flex lg:flex-col lg:justify-center h-full ml-6">
          <div className="flex space-x-3 h-[44px] justify-start items-center bg-white bg-opacity-10  w-[300px] p-3 rounded-3xl">
            <SearchIcon className="w-6 text-gray-600" />
            <input
              className=" bg-transparent
            placeholder:text-gray-600
            focus:outline-none
            
            "
              placeholder="Search Twitter"
              type={"text"}
            />
          </div>
          <div className="w-[300px] mt-3 h-[500px] bg-white bg-opacity-10 rounded-2xl">
            <h1 className="p-3 font-bold text-xl">What's happening</h1>
            <div className="p-3 relative">
              <DotsHorizontalIcon className="w-5 text-gray-600 absolute right-4" />
              <p className="text-xs text-gray-500">Trending in US</p>
              <h1 className="text-[15px] font-bold">China</h1>
              <p className="text-xs text-gray-500">340K Tweets</p>
            </div>

            <div className="p-3 relative">
              <DotsHorizontalIcon className="w-5 text-gray-600 absolute right-4" />
              <p className="text-xs text-gray-500">Trending in US</p>
              <h1 className="text-[15px] font-bold">Apple</h1>
              <p className="text-xs text-gray-500">140K Tweets</p>
            </div>

            <div className="p-3 relative">
              <DotsHorizontalIcon className="w-5 text-gray-600 absolute right-4" />
              <p className="text-xs text-gray-500">Trending in US</p>
              <h1 className="text-[15px] font-bold">Elon Musk</h1>
              <p className="text-xs text-gray-500">30K Tweets</p>
            </div>

            <div className="p-3 relative">
              <DotsHorizontalIcon className="w-5 text-gray-600 absolute right-4" />
              <p className="text-xs text-gray-500">Trending in US</p>
              <h1 className="text-[15px] font-bold">Frontend Simplified</h1>
              <p className="text-xs text-gray-500">14K Tweets</p>
            </div>

            <div className="p-3 relative">
              <DotsHorizontalIcon className="w-5 text-gray-600 absolute right-4" />
              <p className="text-xs text-gray-500">Trending in US</p>
              <h1 className="text-[15px] font-bold">Anime</h1>
              <p className="text-xs text-gray-500">10K Tweets</p>
            </div>
          </div>

          <div className="w-[300px] mt-3 h-[300px] bg-white bg-opacity-10 rounded-2xl">
            <h1 className="p-3 font-bold text-xl">Who to follow</h1>
            <div className="p-3 relative flex justify-between">
              <div className="flex space-x-3">
                <img
                  className="w-11 h-11 object-cover rounded-full"
                  src="./assets/pfp.png"
                />
                <div className="flex flex-col">
                  <div className="flex space-x-1">
                    <h1 className="font-bold text-sm">Elon Musk</h1>
                    <BadgeCheckIcon className="w-[18px] text-blue-400" />
                  </div>{" "}
                  <h1 className="text-[12px] mt-1 text-gray-500">@elonmusk</h1>
                </div>
              </div>
              <button className="bg-white font-bold text-black text-sm w-20 rounded-3xl h-8">
                Follow
              </button>
            </div>

            <div className="p-3 relative flex justify-between">
              <div className="flex space-x-3">
                <img
                  className="w-11 h-11 object-cover rounded-full"
                  src="./assets/bragg.png"
                />
                <div className="flex flex-col">
                  <div className="flex space-x-1">
                    <h1 className="font-bold text-sm">David Bragg</h1>
                    <BadgeCheckIcon className="w-[18px] text-blue-400" />
                  </div>
                  <h1 className="text-[12px] mt-1 text-gray-500">
                    @davidbragg
                  </h1>
                </div>
              </div>
              <button className="bg-white font-bold text-black text-sm w-20 rounded-3xl h-8">
                Follow
              </button>
            </div>

            <div className="p-3 relative flex justify-between">
              <div className="flex space-x-3">
                <img
                  className="w-11 h-11 object-cover rounded-full"
                  src="./assets/kylie.png"
                />
                <div className="flex flex-col">
                  <div className="flex space-x-1">
                    <h1 className="font-bold text-sm">Kylie Jenner</h1>
                    <BadgeCheckIcon className="w-[18px] text-blue-400" />
                  </div>
                  <h1 className="text-[12px] mt-1 text-gray-500">@kylie</h1>
                </div>
              </div>
              <button className="bg-white font-bold text-black text-sm w-20 rounded-3xl h-8">
                Follow
              </button>
            </div>
          </div>
        </div>
      </main>

      {!user.username && (
        <div className="fixed bg-[#1D9BF0] w-full h-[80px] bottom-0 flex justify-center xl:space-x-[200px] items-center">
          <div className="hidden xl:inline">
            <h1 className="text-2xl font-bold">
              Don’t miss what’s happening <br />
            </h1>
            <span className="text-[18px] font-normal">
              People on Twitter are the first to know.
            </span>
          </div>
          <div className="flex space-x-3">
            <LoginModal />
            <SignupModal />
          </div>
        </div>
      )}

      <CommentModal data={tweet} />
    </div>
  );
}
